// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: agent_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_service_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_agent_service_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1, 0}
}

type TurnResponse_EventType int32

const (
	TurnResponse_THOUGHT_CHUNK      TurnResponse_EventType = 0
	TurnResponse_TEXT_CHUNK         TurnResponse_EventType = 1
	TurnResponse_TOOL_CALL_STARTED  TurnResponse_EventType = 2
	TurnResponse_TOOL_CALL_FINISHED TurnResponse_EventType = 3
	TurnResponse_SUBAGENT_SPAWNED   TurnResponse_EventType = 4
	TurnResponse_TURN_COMPLETED     TurnResponse_EventType = 5
	TurnResponse_ERROR              TurnResponse_EventType = 6
)

// Enum value maps for TurnResponse_EventType.
var (
	TurnResponse_EventType_name = map[int32]string{
		0: "THOUGHT_CHUNK",
		1: "TEXT_CHUNK",
		2: "TOOL_CALL_STARTED",
		3: "TOOL_CALL_FINISHED",
		4: "SUBAGENT_SPAWNED",
		5: "TURN_COMPLETED",
		6: "ERROR",
	}
	TurnResponse_EventType_value = map[string]int32{
		"THOUGHT_CHUNK":      0,
		"TEXT_CHUNK":         1,
		"TOOL_CALL_STARTED":  2,
		"TOOL_CALL_FINISHED": 3,
		"SUBAGENT_SPAWNED":   4,
		"TURN_COMPLETED":     5,
		"ERROR":              6,
	}
)

func (x TurnResponse_EventType) Enum() *TurnResponse_EventType {
	p := new(TurnResponse_EventType)
	*p = x
	return p
}

func (x TurnResponse_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TurnResponse_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_service_proto_enumTypes[1].Descriptor()
}

func (TurnResponse_EventType) Type() protoreflect.EnumType {
	return &file_agent_service_proto_enumTypes[1]
}

func (x TurnResponse_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TurnResponse_EventType.Descriptor instead.
func (TurnResponse_EventType) EnumDescriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=clawcrew.agent.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type TurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // References agent TOML configuration
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ContextWindow []byte                 `protobuf:"bytes,4,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnRequest) Reset() {
	*x = TurnRequest{}
	mi := &file_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnRequest) ProtoMessage() {}

func (x *TurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnRequest.ProtoReflect.Descriptor instead.
func (*TurnRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *TurnRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TurnRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TurnRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TurnRequest) GetContextWindow() []byte {
	if x != nil {
		return x.ContextWindow
	}
	return nil
}

type TurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TurnResponse_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=clawcrew.agent.TurnResponse_EventType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                               // Chunk text or JSON payload
	SubagentId    string                 `protobuf:"bytes,3,opt,name=subagent_id,json=subagentId,proto3" json:"subagent_id,omitempty"`       // Populated when event originates from a sub-agent
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error details when type == ERROR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnResponse) Reset() {
	*x = TurnResponse{}
	mi := &file_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnResponse) ProtoMessage() {}

func (x *TurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnResponse.ProtoReflect.Descriptor instead.
func (*TurnResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *TurnResponse) GetType() TurnResponse_EventType {
	if x != nil {
		return x.Type
	}
	return TurnResponse_THOUGHT_CHUNK
}

func (x *TurnResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TurnResponse) GetSubagentId() string {
	if x != nil {
		return x.SubagentId
	}
	return ""
}

func (x *TurnResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*QueryMatch          `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetMatches() []*QueryMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type QueryMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMatch) Reset() {
	*x = QueryMatch{}
	mi := &file_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMatch) ProtoMessage() {}

func (x *QueryMatch) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMatch.ProtoReflect.Descriptor instead.
func (*QueryMatch) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *QueryMatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryMatch) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QueryMatch) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *QueryMatch) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ToolCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"` // e.g. "bash", "write_to_file", "read_file"
	ArgumentsJson string                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallRequest) Reset() {
	*x = ToolCallRequest{}
	mi := &file_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRequest) ProtoMessage() {}

func (x *ToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRequest.ProtoReflect.Descriptor instead.
func (*ToolCallRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCallRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ToolCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallResponse) Reset() {
	*x = ToolCallResponse{}
	mi := &file_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResponse) ProtoMessage() {}

func (x *ToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallResponse.ProtoReflect.Descriptor instead.
func (*ToolCallResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *ToolCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolCallResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolCallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRequest) Reset() {
	*x = SecretRequest{}
	mi := &file_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRequest) ProtoMessage() {}

func (x *SecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRequest.ProtoReflect.Descriptor instead.
func (*SecretRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *SecretRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

type SecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretResponse) Reset() {
	*x = SecretResponse{}
	mi := &file_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretResponse) ProtoMessage() {}

func (x *SecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretResponse.ProtoReflect.Descriptor instead.
func (*SecretResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *SecretResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *SecretResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_agent_service_proto protoreflect.FileDescriptor

const file_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x13agent_service.proto\x12\x0eclawcrew.agent\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x9c\x01\n" +
	"\x13HealthCheckResponse\x12I\n" +
	"\x06status\x18\x01 \x01(\x0e21.clawcrew.agent.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"\x86\x01\n" +
	"\vTurnRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12%\n" +
	"\x0econtext_window\x18\x04 \x01(\fR\rcontextWindow\"\xbf\x02\n" +
	"\fTurnResponse\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.clawcrew.agent.TurnResponse.EventTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vsubagent_id\x18\x03 \x01(\tR\n" +
	"subagentId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x92\x01\n" +
	"\tEventType\x12\x11\n" +
	"\rTHOUGHT_CHUNK\x10\x00\x12\x0e\n" +
	"\n" +
	"TEXT_CHUNK\x10\x01\x12\x15\n" +
	"\x11TOOL_CALL_STARTED\x10\x02\x12\x16\n" +
	"\x12TOOL_CALL_FINISHED\x10\x03\x12\x14\n" +
	"\x10SUBAGENT_SPAWNED\x10\x04\x12\x12\n" +
	"\x0eTURN_COMPLETED\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06\"Y\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"E\n" +
	"\rQueryResponse\x124\n" +
	"\amatches\x18\x01 \x03(\v2\x1a.clawcrew.agent.QueryMatchR\amatches\"\xcf\x01\n" +
	"\n" +
	"QueryMatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12D\n" +
	"\bmetadata\x18\x04 \x03(\v2(.clawcrew.agent.QueryMatch.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x0fToolCallRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\"Z\n" +
	"\x10ToolCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"*\n" +
	"\rSecretRequest\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\"<\n" +
	"\x0eSecretResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\xfa\x01\n" +
	"\vAgentEngine\x12H\n" +
	"\tStartTurn\x12\x1b.clawcrew.agent.TurnRequest\x1a\x1c.clawcrew.agent.TurnResponse0\x01\x12I\n" +
	"\n" +
	"QuickQuery\x12\x1c.clawcrew.agent.QueryRequest\x1a\x1d.clawcrew.agent.QueryResponse\x12V\n" +
	"\vHealthCheck\x12\".clawcrew.agent.HealthCheckRequest\x1a#.clawcrew.agent.HealthCheckResponse2\xbc\x01\n" +
	"\rSystemGateway\x12V\n" +
	"\x11ExecuteNativeTool\x12\x1f.clawcrew.agent.ToolCallRequest\x1a .clawcrew.agent.ToolCallResponse\x12S\n" +
	"\x12GetDecryptedSecret\x12\x1d.clawcrew.agent.SecretRequest\x1a\x1e.clawcrew.agent.SecretResponseB2Z0github.com/diezy-labs/claw-crew/engine/pkg/pb;pbb\x06proto3"

var (
	file_agent_service_proto_rawDescOnce sync.Once
	file_agent_service_proto_rawDescData []byte
)

func file_agent_service_proto_rawDescGZIP() []byte {
	file_agent_service_proto_rawDescOnce.Do(func() {
		file_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)))
	})
	return file_agent_service_proto_rawDescData
}

var file_agent_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_service_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: clawcrew.agent.HealthCheckResponse.ServingStatus
	(TurnResponse_EventType)(0),            // 1: clawcrew.agent.TurnResponse.EventType
	(*HealthCheckRequest)(nil),             // 2: clawcrew.agent.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 3: clawcrew.agent.HealthCheckResponse
	(*TurnRequest)(nil),                    // 4: clawcrew.agent.TurnRequest
	(*TurnResponse)(nil),                   // 5: clawcrew.agent.TurnResponse
	(*QueryRequest)(nil),                   // 6: clawcrew.agent.QueryRequest
	(*QueryResponse)(nil),                  // 7: clawcrew.agent.QueryResponse
	(*QueryMatch)(nil),                     // 8: clawcrew.agent.QueryMatch
	(*ToolCallRequest)(nil),                // 9: clawcrew.agent.ToolCallRequest
	(*ToolCallResponse)(nil),               // 10: clawcrew.agent.ToolCallResponse
	(*SecretRequest)(nil),                  // 11: clawcrew.agent.SecretRequest
	(*SecretResponse)(nil),                 // 12: clawcrew.agent.SecretResponse
	nil,                                    // 13: clawcrew.agent.QueryMatch.MetadataEntry
}
var file_agent_service_proto_depIdxs = []int32{
	0,  // 0: clawcrew.agent.HealthCheckResponse.status:type_name -> clawcrew.agent.HealthCheckResponse.ServingStatus
	1,  // 1: clawcrew.agent.TurnResponse.type:type_name -> clawcrew.agent.TurnResponse.EventType
	8,  // 2: clawcrew.agent.QueryResponse.matches:type_name -> clawcrew.agent.QueryMatch
	13, // 3: clawcrew.agent.QueryMatch.metadata:type_name -> clawcrew.agent.QueryMatch.MetadataEntry
	4,  // 4: clawcrew.agent.AgentEngine.StartTurn:input_type -> clawcrew.agent.TurnRequest
	6,  // 5: clawcrew.agent.AgentEngine.QuickQuery:input_type -> clawcrew.agent.QueryRequest
	2,  // 6: clawcrew.agent.AgentEngine.HealthCheck:input_type -> clawcrew.agent.HealthCheckRequest
	9,  // 7: clawcrew.agent.SystemGateway.ExecuteNativeTool:input_type -> clawcrew.agent.ToolCallRequest
	11, // 8: clawcrew.agent.SystemGateway.GetDecryptedSecret:input_type -> clawcrew.agent.SecretRequest
	5,  // 9: clawcrew.agent.AgentEngine.StartTurn:output_type -> clawcrew.agent.TurnResponse
	7,  // 10: clawcrew.agent.AgentEngine.QuickQuery:output_type -> clawcrew.agent.QueryResponse
	3,  // 11: clawcrew.agent.AgentEngine.HealthCheck:output_type -> clawcrew.agent.HealthCheckResponse
	10, // 12: clawcrew.agent.SystemGateway.ExecuteNativeTool:output_type -> clawcrew.agent.ToolCallResponse
	12, // 13: clawcrew.agent.SystemGateway.GetDecryptedSecret:output_type -> clawcrew.agent.SecretResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_service_proto_init() }
func file_agent_service_proto_init() {
	if File_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_service_proto_goTypes,
		DependencyIndexes: file_agent_service_proto_depIdxs,
		EnumInfos:         file_agent_service_proto_enumTypes,
		MessageInfos:      file_agent_service_proto_msgTypes,
	}.Build()
	File_agent_service_proto = out.File
	file_agent_service_proto_goTypes = nil
	file_agent_service_proto_depIdxs = nil
}
