// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: agent_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentEngine_StartTurn_FullMethodName   = "/clawcrew.agent.AgentEngine/StartTurn"
	AgentEngine_QuickQuery_FullMethodName  = "/clawcrew.agent.AgentEngine/QuickQuery"
	AgentEngine_HealthCheck_FullMethodName = "/clawcrew.agent.AgentEngine/HealthCheck"
)

// AgentEngineClient is the client API for AgentEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service hosted by Go (AI Brain) and invoked by Rust (UI/Gateway)
type AgentEngineClient interface {
	// Starts a new turn/task for an Agent, returning a stream of responses
	StartTurn(ctx context.Context, in *TurnRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TurnResponse], error)
	// Executes a quick query without full state persistence (e.g., RAG vector search)
	QuickQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// gRPC health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type agentEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentEngineClient(cc grpc.ClientConnInterface) AgentEngineClient {
	return &agentEngineClient{cc}
}

func (c *agentEngineClient) StartTurn(ctx context.Context, in *TurnRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TurnResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentEngine_ServiceDesc.Streams[0], AgentEngine_StartTurn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TurnRequest, TurnResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentEngine_StartTurnClient = grpc.ServerStreamingClient[TurnResponse]

func (c *agentEngineClient) QuickQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, AgentEngine_QuickQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentEngineClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AgentEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentEngineServer is the server API for AgentEngine service.
// All implementations must embed UnimplementedAgentEngineServer
// for forward compatibility.
//
// Service hosted by Go (AI Brain) and invoked by Rust (UI/Gateway)
type AgentEngineServer interface {
	// Starts a new turn/task for an Agent, returning a stream of responses
	StartTurn(*TurnRequest, grpc.ServerStreamingServer[TurnResponse]) error
	// Executes a quick query without full state persistence (e.g., RAG vector search)
	QuickQuery(context.Context, *QueryRequest) (*QueryResponse, error)
	// gRPC health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAgentEngineServer()
}

// UnimplementedAgentEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentEngineServer struct{}

func (UnimplementedAgentEngineServer) StartTurn(*TurnRequest, grpc.ServerStreamingServer[TurnResponse]) error {
	return status.Error(codes.Unimplemented, "method StartTurn not implemented")
}
func (UnimplementedAgentEngineServer) QuickQuery(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuickQuery not implemented")
}
func (UnimplementedAgentEngineServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAgentEngineServer) mustEmbedUnimplementedAgentEngineServer() {}
func (UnimplementedAgentEngineServer) testEmbeddedByValue()                     {}

// UnsafeAgentEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentEngineServer will
// result in compilation errors.
type UnsafeAgentEngineServer interface {
	mustEmbedUnimplementedAgentEngineServer()
}

func RegisterAgentEngineServer(s grpc.ServiceRegistrar, srv AgentEngineServer) {
	// If the following call panics, it indicates UnimplementedAgentEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentEngine_ServiceDesc, srv)
}

func _AgentEngine_StartTurn_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TurnRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentEngineServer).StartTurn(m, &grpc.GenericServerStream[TurnRequest, TurnResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentEngine_StartTurnServer = grpc.ServerStreamingServer[TurnResponse]

func _AgentEngine_QuickQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEngineServer).QuickQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEngine_QuickQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEngineServer).QuickQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEngineServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentEngine_ServiceDesc is the grpc.ServiceDesc for AgentEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawcrew.agent.AgentEngine",
	HandlerType: (*AgentEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuickQuery",
			Handler:    _AgentEngine_QuickQuery_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AgentEngine_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartTurn",
			Handler:       _AgentEngine_StartTurn_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent_service.proto",
}

const (
	SystemGateway_ExecuteNativeTool_FullMethodName  = "/clawcrew.agent.SystemGateway/ExecuteNativeTool"
	SystemGateway_GetDecryptedSecret_FullMethodName = "/clawcrew.agent.SystemGateway/GetDecryptedSecret"
	SystemGateway_ExecuteTask_FullMethodName        = "/clawcrew.agent.SystemGateway/ExecuteTask"
)

// SystemGatewayClient is the client API for SystemGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service hosted by Rust (Native System) and invoked by Go (when Agent requires OS tools)
type SystemGatewayClient interface {
	// Requests Rust to execute a native platform tool (terminal, disk access)
	ExecuteNativeTool(ctx context.Context, in *ToolCallRequest, opts ...grpc.CallOption) (*ToolCallResponse, error)
	// Requests a decrypted credential from Rust Secret Vault
	GetDecryptedSecret(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretResponse, error)
	// ExecuteTask route for external task execution (engine -> executor)
	ExecuteTask(ctx context.Context, in *TaskExecutionRequest, opts ...grpc.CallOption) (*TaskExecutionResponse, error)
}

type systemGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemGatewayClient(cc grpc.ClientConnInterface) SystemGatewayClient {
	return &systemGatewayClient{cc}
}

func (c *systemGatewayClient) ExecuteNativeTool(ctx context.Context, in *ToolCallRequest, opts ...grpc.CallOption) (*ToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolCallResponse)
	err := c.cc.Invoke(ctx, SystemGateway_ExecuteNativeTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemGatewayClient) GetDecryptedSecret(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretResponse)
	err := c.cc.Invoke(ctx, SystemGateway_GetDecryptedSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemGatewayClient) ExecuteTask(ctx context.Context, in *TaskExecutionRequest, opts ...grpc.CallOption) (*TaskExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskExecutionResponse)
	err := c.cc.Invoke(ctx, SystemGateway_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemGatewayServer is the server API for SystemGateway service.
// All implementations must embed UnimplementedSystemGatewayServer
// for forward compatibility.
//
// Service hosted by Rust (Native System) and invoked by Go (when Agent requires OS tools)
type SystemGatewayServer interface {
	// Requests Rust to execute a native platform tool (terminal, disk access)
	ExecuteNativeTool(context.Context, *ToolCallRequest) (*ToolCallResponse, error)
	// Requests a decrypted credential from Rust Secret Vault
	GetDecryptedSecret(context.Context, *SecretRequest) (*SecretResponse, error)
	// ExecuteTask route for external task execution (engine -> executor)
	ExecuteTask(context.Context, *TaskExecutionRequest) (*TaskExecutionResponse, error)
	mustEmbedUnimplementedSystemGatewayServer()
}

// UnimplementedSystemGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemGatewayServer struct{}

func (UnimplementedSystemGatewayServer) ExecuteNativeTool(context.Context, *ToolCallRequest) (*ToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteNativeTool not implemented")
}
func (UnimplementedSystemGatewayServer) GetDecryptedSecret(context.Context, *SecretRequest) (*SecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecryptedSecret not implemented")
}
func (UnimplementedSystemGatewayServer) ExecuteTask(context.Context, *TaskExecutionRequest) (*TaskExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedSystemGatewayServer) mustEmbedUnimplementedSystemGatewayServer() {}
func (UnimplementedSystemGatewayServer) testEmbeddedByValue()                       {}

// UnsafeSystemGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemGatewayServer will
// result in compilation errors.
type UnsafeSystemGatewayServer interface {
	mustEmbedUnimplementedSystemGatewayServer()
}

func RegisterSystemGatewayServer(s grpc.ServiceRegistrar, srv SystemGatewayServer) {
	// If the following call panics, it indicates UnimplementedSystemGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemGateway_ServiceDesc, srv)
}

func _SystemGateway_ExecuteNativeTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemGatewayServer).ExecuteNativeTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemGateway_ExecuteNativeTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemGatewayServer).ExecuteNativeTool(ctx, req.(*ToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemGateway_GetDecryptedSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemGatewayServer).GetDecryptedSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemGateway_GetDecryptedSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemGatewayServer).GetDecryptedSecret(ctx, req.(*SecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemGateway_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemGatewayServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemGateway_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemGatewayServer).ExecuteTask(ctx, req.(*TaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemGateway_ServiceDesc is the grpc.ServiceDesc for SystemGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawcrew.agent.SystemGateway",
	HandlerType: (*SystemGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteNativeTool",
			Handler:    _SystemGateway_ExecuteNativeTool_Handler,
		},
		{
			MethodName: "GetDecryptedSecret",
			Handler:    _SystemGateway_GetDecryptedSecret_Handler,
		},
		{
			MethodName: "ExecuteTask",
			Handler:    _SystemGateway_ExecuteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_service.proto",
}
