// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/diezy-labs/claw-crew/engine/core/config"
	"github.com/diezy-labs/claw-crew/engine/src/crew"
)

// Injectors from wire.go:

// InitializeApp membangun dependency graph menggunakan Google Wire
func InitializeApp(cfg *config.AppConfig) (*App, error) {
	server := NewGRPCServer()
	metricsServer := ProvideMetricsServer(cfg)
	orchestrator := crew.NewService()
	grpcHandler := crew.NewGRPCHandler(orchestrator)
	app := NewApp(cfg, server, metricsServer, grpcHandler)
	return app, nil
}
