// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"path/filepath"

	"github.com/diezy-labs/claw-crew/engine/core/config"
	"github.com/diezy-labs/claw-crew/engine/pkg/client"
	"github.com/diezy-labs/claw-crew/engine/src/artifact"
	"github.com/diezy-labs/claw-crew/engine/src/crew"
	"github.com/diezy-labs/claw-crew/engine/src/fleet"
	"github.com/diezy-labs/claw-crew/engine/src/llm"
	"github.com/diezy-labs/claw-crew/engine/src/memory"
	qmorch "github.com/diezy-labs/claw-crew/engine/src/orchestrator"
	"github.com/diezy-labs/claw-crew/engine/src/persistence"
	"github.com/diezy-labs/claw-crew/engine/src/run"
	"github.com/diezy-labs/claw-crew/engine/src/task"
	"github.com/diezy-labs/claw-crew/engine/src/tool"
	"github.com/diezy-labs/claw-crew/engine/src/workflow"
)

// Injectors from wire.go:

// InitializeApp builds the dependency injection graph via Google Wire
func InitializeApp(cfg *config.AppConfig) (*App, error) {
	server := NewGRPCServer()
	metricsServer := ProvideMetricsServer(cfg)
	systemGatewayClient, err := client.ProvideSystemGatewayClient(cfg)
	if err != nil {
		return nil, err
	}
	provider := llm.NewProvider(cfg, systemGatewayClient)
	toolDispatcher := llm.NewToolDispatcher(systemGatewayClient)
	orchestrator := crew.NewService(provider, toolDispatcher, systemGatewayClient)
	vectorStore := memory.NewVectorStore()
	crewRegistry := crew.NewRegistry()
	grpcHandler := crew.NewGRPCHandler(orchestrator, vectorStore, crewRegistry)
	memoryStore, err := persistence.NewDiskStore(filepath.Join(cfg.DataDir, "runs-store"))
	if err != nil {
		return nil, err
	}
	memoryEventHub := run.NewEventHub()
	runService := run.NewService(memoryStore, memoryEventHub)
	runHTTPHandler := run.NewHTTPHandler(runService)
	taskStore, err := persistence.NewDiskTaskStore(cfg.DataDir)
	if err != nil {
		return nil, err
	}
	taskScheduler := task.NewScheduler()
	taskService := task.NewService(taskStore, taskScheduler, runService)
	taskHTTPHandler := task.NewHTTPHandler(taskService)
	toolRegistry := tool.NewRegistry()
	toolGate := tool.NewApprovalGate(runService)
	// F3-1: route native builtin tool execution through the Rust SystemGateway
	// (:50052) so bash/read_file/write/git run inside the Landlock sandbox, not
	// in-process. The client structurally satisfies tool.SystemGateway; a nil/
	// unavailable gateway falls back to in-process execution inside the client.
	toolService := tool.NewService(toolRegistry, toolGate, runService).WithSystemGateway(systemGatewayClient)
	toolHTTPHandler := tool.NewHTTPHandler(toolService)
	artifactRepo, err := persistence.NewDiskArtifactStore(cfg.DataDir)
	if err != nil {
		return nil, err
	}
	artifactService := artifact.NewService(artifactRepo, runService)
	artifactHTTPHandler := artifact.NewHTTPHandler(artifactService)
	workflowRegistry := workflow.NewRegistry()
	workflowService := workflow.NewService(workflowRegistry, taskService)
	workflowHTTPHandler := workflow.NewHTTPHandler(workflowService)
	fleetService := fleet.NewService(provider)
	objectiveProposer := qmorch.NewService(provider, fleetService)
	fleetService.SetObjectiveProposer(objectiveProposer)
	fleetHTTPHandler := fleet.NewHTTPHandler(fleetService)
	app := NewApp(cfg, server, metricsServer, grpcHandler, runHTTPHandler, taskHTTPHandler, toolHTTPHandler, artifactHTTPHandler, workflowHTTPHandler, fleetHTTPHandler)
	return app, nil
}
